import "react";

// Generated using https://www.json-generator.com/
const someData = [
  {
    _id: "614c9c10b7d3530052d967ee",
    index: 0,
    guid: "b56c1208-6602-49cb-8f8a-cb4a7e5fa4d1",
    isActive: false,
    balance: "$2,606.98",
    picture: "http://placehold.it/32x32",
    age: 29,
    eyeColor: "brown",
    name: "Krista Singleton",
    gender: "female",
    company: "CUBICIDE",
    email: "kristasingleton@cubicide.com",
    phone: "+1 (964) 467-3208",
    address: "463 Hoyts Lane, Morgandale, Pennsylvania, 6248",
    about:
      "Veniam nulla velit esse Lorem esse veniam dolore fugiat eiusmod ex incididunt. In consectetur reprehenderit id eiusmod esse mollit eu ut id sint in. Laboris ad veniam mollit aliquip commodo qui ullamco ex incididunt in veniam. Anim do id reprehenderit aliquip ex ex proident cillum ex irure mollit consectetur irure. Labore tempor dolore officia ut. Fugiat magna deserunt excepteur in consectetur occaecat cillum eiusmod veniam. Eu irure eiusmod voluptate id culpa pariatur velit sunt occaecat culpa adipisicing excepteur dolor.\r\n",
    registered: "2016-04-11T02:46:14 -02:00",
    latitude: 25.730682,
    longitude: 17.503039,
    tags: [
      "culpa",
      "ea",
      "adipisicing",
      "veniam",
      "non",
      "exercitation",
      "proident",
    ],
    friends: [
      {
        id: 0,
        name: "Diaz Robinson",
      },
      {
        id: 1,
        name: "King Rowland",
      },
      {
        id: 2,
        name: "Carey Mcclain",
      },
    ],
    greeting: "Hello, Krista Singleton! You have 10 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "614c9c10d35d30079fddada9",
    index: 1,
    guid: "f90efe0a-8ce7-45d6-900f-00c2ff74d413",
    isActive: true,
    balance: "$3,762.66",
    picture: "http://placehold.it/32x32",
    age: 35,
    eyeColor: "blue",
    name: "Jill Jensen",
    gender: "female",
    company: "ULTRASURE",
    email: "jilljensen@ultrasure.com",
    phone: "+1 (973) 400-2507",
    address: "908 Hegeman Avenue, Kaka, Wyoming, 3491",
    about:
      "Commodo amet commodo officia sint deserunt reprehenderit dolor in cupidatat dolor dolore. Sit eu ipsum eu officia magna. Cillum officia est cillum in culpa. Reprehenderit elit ut ipsum exercitation labore excepteur ex nisi ad culpa minim amet qui. Ipsum quis ex velit excepteur id. Id ex elit nisi aliqua commodo amet non mollit do aliquip est dolore laboris veniam.\r\n",
    registered: "2014-12-20T10:08:39 -01:00",
    latitude: -52.543211,
    longitude: -83.459002,
    tags: ["nisi", "et", "sit", "occaecat", "eu", "occaecat", "nulla"],
    friends: [
      {
        id: 0,
        name: "Abigail Kelly",
      },
      {
        id: 1,
        name: "Monica Carson",
      },
      {
        id: 2,
        name: "Chaney Collier",
      },
    ],
    greeting: "Hello, Jill Jensen! You have 5 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "614c9c10a076682144864462",
    index: 2,
    guid: "487eb398-5b9a-45dc-bd31-52d1a960dac4",
    isActive: true,
    balance: "$1,860.58",
    picture: "http://placehold.it/32x32",
    age: 34,
    eyeColor: "green",
    name: "Spears Greene",
    gender: "male",
    company: "ELENTRIX",
    email: "spearsgreene@elentrix.com",
    phone: "+1 (831) 592-3160",
    address: "571 Elliott Walk, Dexter, Illinois, 6974",
    about:
      "Cillum commodo cillum exercitation excepteur adipisicing elit minim aliquip quis id laborum. Deserunt ea ex ullamco fugiat eiusmod do. Et laboris eiusmod deserunt Lorem velit ea tempor veniam dolore pariatur. Eiusmod nostrud ea ut sit nulla esse reprehenderit fugiat aliquip ea esse. Anim anim deserunt et labore qui.\r\n",
    registered: "2019-08-25T01:56:49 -02:00",
    latitude: 67.492484,
    longitude: 48.64994,
    tags: ["ipsum", "do", "ipsum", "officia", "ipsum", "irure", "et"],
    friends: [
      {
        id: 0,
        name: "Suzette James",
      },
      {
        id: 1,
        name: "Isabelle Mcguire",
      },
      {
        id: 2,
        name: "Kline Alston",
      },
    ],
    greeting: "Hello, Spears Greene! You have 1 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "614c9c10541bb4ba0a3c426b",
    index: 3,
    guid: "ea2ffde6-9368-4a89-85e6-f803c038435a",
    isActive: false,
    balance: "$1,311.24",
    picture: "http://placehold.it/32x32",
    age: 31,
    eyeColor: "brown",
    name: "Brandy Baker",
    gender: "female",
    company: "PORTALINE",
    email: "brandybaker@portaline.com",
    phone: "+1 (914) 519-3369",
    address: "149 Revere Place, Mulino, New Jersey, 2033",
    about:
      "Commodo elit do nostrud qui ad. Ea occaecat in do incididunt consectetur. In eiusmod ullamco id aute nisi ipsum laboris. Ex excepteur incididunt commodo duis. Ad duis sint est nisi. Ea aute dolor labore Lorem voluptate consequat consequat id ad aliqua anim culpa consequat.\r\n",
    registered: "2021-02-08T06:25:12 -01:00",
    latitude: -26.336663,
    longitude: -111.324357,
    tags: ["velit", "quis", "elit", "sit", "sunt", "incididunt", "magna"],
    friends: [
      {
        id: 0,
        name: "Ines Sanchez",
      },
      {
        id: 1,
        name: "Medina Cole",
      },
      {
        id: 2,
        name: "Frazier Wilder",
      },
    ],
    greeting: "Hello, Brandy Baker! You have 7 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "614c9c10cd99134e2aa0b4e0",
    index: 4,
    guid: "24e08903-c687-4921-8d28-ba3a325c8e5d",
    isActive: true,
    balance: "$2,277.22",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "brown",
    name: "Fowler Sullivan",
    gender: "male",
    company: "MOLTONIC",
    email: "fowlersullivan@moltonic.com",
    phone: "+1 (818) 585-2604",
    address: "144 Harbor Court, Gorham, Texas, 7665",
    about:
      "Commodo in fugiat irure nostrud proident amet minim. Aute officia consequat ea id et proident. Commodo sit est incididunt laboris et culpa enim ex aliquip esse. Fugiat quis anim ex consectetur. Aliquip exercitation ea cupidatat ex excepteur aliqua aliqua esse non eu ex.\r\n",
    registered: "2014-04-17T07:28:18 -02:00",
    latitude: -47.565838,
    longitude: 102.618956,
    tags: ["anim", "anim", "eiusmod", "labore", "commodo", "velit", "dolore"],
    friends: [
      {
        id: 0,
        name: "Marcia Scott",
      },
      {
        id: 1,
        name: "Dorthy Delacruz",
      },
      {
        id: 2,
        name: "Lily Newton",
      },
    ],
    greeting: "Hello, Fowler Sullivan! You have 10 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "614c9c10176699912242f9e1",
    index: 5,
    guid: "47c178e7-1672-46bd-a1c9-c2ea575b8979",
    isActive: false,
    balance: "$1,714.14",
    picture: "http://placehold.it/32x32",
    age: 39,
    eyeColor: "green",
    name: "Henry Dunlap",
    gender: "male",
    company: "AVENETRO",
    email: "henrydunlap@avenetro.com",
    phone: "+1 (847) 532-3519",
    address: "330 Classon Avenue, Disautel, North Carolina, 9238",
    about:
      "Pariatur duis dolore laborum tempor culpa sit aliquip aliquip culpa magna. Commodo incididunt fugiat incididunt fugiat cupidatat pariatur est sunt aliqua eu proident aliquip. Proident laborum eiusmod quis amet deserunt occaecat dolore eu laboris duis laboris est occaecat voluptate. In mollit veniam non aliquip Lorem. Esse non ullamco nostrud deserunt do sunt. Ea sit sit consequat aute amet nulla veniam aliquip exercitation excepteur aliquip.\r\n",
    registered: "2015-06-05T11:46:59 -02:00",
    latitude: 12.526317,
    longitude: -87.270929,
    tags: [
      "incididunt",
      "non",
      "nostrud",
      "qui",
      "voluptate",
      "irure",
      "ullamco",
    ],
    friends: [
      {
        id: 0,
        name: "Ada Riggs",
      },
      {
        id: 1,
        name: "Barry Mathis",
      },
      {
        id: 2,
        name: "Arnold Briggs",
      },
    ],
    greeting: "Hello, Henry Dunlap! You have 4 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "614c9c10fb1c676656d98574",
    index: 6,
    guid: "24e0dade-a1dc-49b7-ab23-abba16fc2fc1",
    isActive: true,
    balance: "$2,752.20",
    picture: "http://placehold.it/32x32",
    age: 38,
    eyeColor: "brown",
    name: "Florence Martin",
    gender: "female",
    company: "MOMENTIA",
    email: "florencemartin@momentia.com",
    phone: "+1 (987) 599-2084",
    address: "565 Clinton Street, Fruitdale, Maryland, 5868",
    about:
      "Magna commodo nisi tempor aliqua commodo cillum consequat eiusmod ea magna irure. Culpa do amet non nisi officia laborum dolor enim nisi tempor excepteur veniam. Fugiat magna culpa fugiat ut consequat magna. Ea non commodo ex eu ad do tempor est occaecat qui fugiat. Ea enim incididunt consectetur veniam est laboris.\r\n",
    registered: "2017-01-19T09:05:13 -01:00",
    latitude: 58.264278,
    longitude: -139.754306,
    tags: ["dolor", "commodo", "nisi", "voluptate", "esse", "veniam", "sit"],
    friends: [
      {
        id: 0,
        name: "Camille Nixon",
      },
      {
        id: 1,
        name: "Loraine Booker",
      },
      {
        id: 2,
        name: "Alyson Levine",
      },
    ],
    greeting: "Hello, Florence Martin! You have 4 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "614c9c1080a8aa25f74066c7",
    index: 7,
    guid: "303e6725-f647-4cb4-84c2-0225bef6f0f4",
    isActive: true,
    balance: "$2,999.03",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "brown",
    name: "Owens Hunter",
    gender: "male",
    company: "BITREX",
    email: "owenshunter@bitrex.com",
    phone: "+1 (886) 429-2996",
    address: "846 Graham Avenue, Wheaton, Connecticut, 8456",
    about:
      "Veniam nisi sint adipisicing ad sint nulla. Aute consectetur aliquip exercitation exercitation irure in in tempor excepteur veniam ullamco nulla amet laborum. Aliquip reprehenderit amet do cillum consequat et ea adipisicing deserunt consectetur aliqua. Veniam laborum adipisicing tempor commodo minim aute nisi proident reprehenderit voluptate commodo velit. Aliqua officia sit laborum ea labore mollit duis non adipisicing cillum cupidatat ex. Consectetur id ullamco sunt in cupidatat aliquip laboris. Fugiat ullamco esse eu laborum anim eu nisi labore reprehenderit ut ullamco.\r\n",
    registered: "2021-04-27T06:44:37 -02:00",
    latitude: -66.239272,
    longitude: -60.473706,
    tags: ["sunt", "qui", "nostrud", "id", "culpa", "elit", "eiusmod"],
    friends: [
      {
        id: 0,
        name: "Janell Kidd",
      },
      {
        id: 1,
        name: "Cherry Davenport",
      },
      {
        id: 2,
        name: "Nicholson Dixon",
      },
    ],
    greeting: "Hello, Owens Hunter! You have 10 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "614c9c10f890c229790d69f0",
    index: 8,
    guid: "bb2e0476-0fcb-47f8-9f25-bc449c4e772b",
    isActive: false,
    balance: "$1,092.96",
    picture: "http://placehold.it/32x32",
    age: 38,
    eyeColor: "green",
    name: "Ellis Shannon",
    gender: "male",
    company: "FRANSCENE",
    email: "ellisshannon@franscene.com",
    phone: "+1 (945) 447-3925",
    address: "410 Bayard Street, Waverly, Maine, 1575",
    about:
      "Adipisicing cupidatat incididunt aliqua eiusmod ipsum nisi nostrud nisi ad minim. Et laborum culpa laboris cupidatat labore commodo aliquip. Excepteur id mollit amet velit minim id quis do proident amet ex ullamco sit consectetur. Elit ullamco veniam aliquip aliqua magna pariatur commodo. Occaecat nisi velit esse enim laborum nostrud. Sunt do nulla exercitation do tempor. Exercitation eiusmod esse amet fugiat minim adipisicing amet deserunt cillum eu quis enim excepteur aute.\r\n",
    registered: "2019-10-10T05:12:47 -02:00",
    latitude: -49.949479,
    longitude: -94.83095,
    tags: ["reprehenderit", "eu", "et", "ad", "anim", "aute", "minim"],
    friends: [
      {
        id: 0,
        name: "Chavez Mills",
      },
      {
        id: 1,
        name: "Tanner Fisher",
      },
      {
        id: 2,
        name: "Anita Pitts",
      },
    ],
    greeting: "Hello, Ellis Shannon! You have 7 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "614c9c10e28d8d0fb9a5d1cc",
    index: 9,
    guid: "55076f77-60ab-422a-bdba-6fbdbed81556",
    isActive: true,
    balance: "$2,641.81",
    picture: "http://placehold.it/32x32",
    age: 36,
    eyeColor: "brown",
    name: "Ericka Clayton",
    gender: "female",
    company: "DIGIQUE",
    email: "erickaclayton@digique.com",
    phone: "+1 (894) 462-2822",
    address: "421 Livonia Avenue, Machias, Delaware, 9948",
    about:
      "Ad labore est labore do aliquip eu quis veniam dolore elit anim est eu. Commodo excepteur qui eiusmod incididunt esse sit mollit reprehenderit enim ipsum duis ex. Consequat pariatur commodo ex reprehenderit ullamco do ut tempor sunt. Ipsum incididunt do adipisicing voluptate. Nulla magna eu id officia eu ea enim aliqua adipisicing do et fugiat.\r\n",
    registered: "2014-05-20T10:10:32 -02:00",
    latitude: 10.168382,
    longitude: -128.508427,
    tags: ["ullamco", "sint", "esse", "fugiat", "ea", "id", "tempor"],
    friends: [
      {
        id: 0,
        name: "Jacquelyn Curtis",
      },
      {
        id: 1,
        name: "Muriel Richmond",
      },
      {
        id: 2,
        name: "Perkins Cooke",
      },
    ],
    greeting: "Hello, Ericka Clayton! You have 5 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "614c9c1074a04c4a00420016",
    index: 10,
    guid: "a55b832d-87dc-4b8d-b012-04216cbf1706",
    isActive: false,
    balance: "$1,817.86",
    picture: "http://placehold.it/32x32",
    age: 27,
    eyeColor: "blue",
    name: "Janelle Cotton",
    gender: "female",
    company: "CYCLONICA",
    email: "janellecotton@cyclonica.com",
    phone: "+1 (933) 563-2777",
    address: "851 Falmouth Street, Sehili, Palau, 4610",
    about:
      "Sint nostrud nulla ea pariatur occaecat et sint cillum dolor nostrud magna aute Lorem. Nostrud sit sunt ipsum ea aute quis. Eiusmod est mollit id reprehenderit commodo dolore nisi ex labore adipisicing. Et excepteur sint ut nostrud ullamco dolore commodo aliquip nulla eu sit magna quis irure. Voluptate id ut cupidatat qui ipsum sunt non amet nisi veniam labore ea ea. Labore non magna deserunt ex anim do incididunt culpa elit laboris aliquip veniam elit. Deserunt magna incididunt aliqua voluptate minim officia enim occaecat ipsum aliquip dolore irure occaecat.\r\n",
    registered: "2014-09-12T10:29:15 -02:00",
    latitude: -28.798257,
    longitude: 60.204817,
    tags: [
      "elit",
      "reprehenderit",
      "Lorem",
      "ad",
      "et",
      "consectetur",
      "nostrud",
    ],
    friends: [
      {
        id: 0,
        name: "Deborah Frank",
      },
      {
        id: 1,
        name: "Short Butler",
      },
      {
        id: 2,
        name: "Adrian Bonner",
      },
    ],
    greeting: "Hello, Janelle Cotton! You have 1 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "614c9c10859831354083b3d7",
    index: 11,
    guid: "a287714d-7a52-47b7-8f85-468326c4acca",
    isActive: false,
    balance: "$3,765.29",
    picture: "http://placehold.it/32x32",
    age: 22,
    eyeColor: "brown",
    name: "Ella Ratliff",
    gender: "female",
    company: "GALLAXIA",
    email: "ellaratliff@gallaxia.com",
    phone: "+1 (915) 599-2762",
    address: "840 Kathleen Court, Kingstowne, Missouri, 2788",
    about:
      "Non excepteur id tempor ad dolore. Do Lorem magna reprehenderit est enim. Amet dolor occaecat anim cupidatat ut nisi velit velit culpa eiusmod.\r\n",
    registered: "2014-11-29T02:41:04 -01:00",
    latitude: 65.775373,
    longitude: -48.663829,
    tags: ["minim", "ex", "Lorem", "cupidatat", "labore", "duis", "anim"],
    friends: [
      {
        id: 0,
        name: "Helga Acosta",
      },
      {
        id: 1,
        name: "Christian Hardin",
      },
      {
        id: 2,
        name: "Little Fitzpatrick",
      },
    ],
    greeting: "Hello, Ella Ratliff! You have 9 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "614c9c108a5708557c797206",
    index: 12,
    guid: "21ed3213-0a18-45ea-a6e9-24005159b7a7",
    isActive: true,
    balance: "$2,943.58",
    picture: "http://placehold.it/32x32",
    age: 23,
    eyeColor: "brown",
    name: "Renee Berger",
    gender: "female",
    company: "FUTURIZE",
    email: "reneeberger@futurize.com",
    phone: "+1 (806) 460-3411",
    address: "626 Llama Court, Toftrees, Virginia, 3785",
    about:
      "Exercitation ut sint mollit qui nisi culpa veniam do dolore velit anim proident nostrud. Id do sint et velit elit dolore non commodo consequat cillum est ipsum pariatur aliqua. Minim aute exercitation cillum velit cupidatat est cupidatat et occaecat ex irure laboris. Lorem voluptate in in ea excepteur amet laborum ea veniam velit elit elit in ea. Magna magna do velit esse laboris cupidatat adipisicing ipsum ex labore exercitation amet. Proident ipsum laboris consequat velit. Consequat amet pariatur consequat ea tempor reprehenderit amet excepteur voluptate nisi irure consequat amet fugiat.\r\n",
    registered: "2020-11-13T12:32:32 -01:00",
    latitude: -7.485082,
    longitude: 26.326461,
    tags: [
      "laborum",
      "nisi",
      "voluptate",
      "dolor",
      "laboris",
      "irure",
      "reprehenderit",
    ],
    friends: [
      {
        id: 0,
        name: "Sparks Sexton",
      },
      {
        id: 1,
        name: "Puckett Cox",
      },
      {
        id: 2,
        name: "Morgan Sosa",
      },
    ],
    greeting: "Hello, Renee Berger! You have 10 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "614c9c1051faec5e117f8191",
    index: 13,
    guid: "950378de-f961-433f-aae5-467a0c70dddc",
    isActive: true,
    balance: "$3,774.22",
    picture: "http://placehold.it/32x32",
    age: 35,
    eyeColor: "blue",
    name: "Eliza Hogan",
    gender: "female",
    company: "SKINSERVE",
    email: "elizahogan@skinserve.com",
    phone: "+1 (951) 489-2154",
    address: "724 Freeman Street, Day, Indiana, 9388",
    about:
      "Enim id cillum consequat ipsum consequat officia sunt laboris excepteur do aliquip in excepteur excepteur. Esse ad anim proident culpa commodo incididunt deserunt tempor commodo pariatur ut sit sunt. Non minim cupidatat sit do eiusmod commodo consequat aliquip voluptate proident et. Voluptate nisi nulla et elit eiusmod nostrud magna non. Fugiat anim labore deserunt Lorem labore qui deserunt.\r\n",
    registered: "2017-11-08T05:28:45 -01:00",
    latitude: -29.642678,
    longitude: 31.723354,
    tags: ["id", "officia", "qui", "mollit", "tempor", "mollit", "amet"],
    friends: [
      {
        id: 0,
        name: "Lelia Perkins",
      },
      {
        id: 1,
        name: "Rene Huffman",
      },
      {
        id: 2,
        name: "Cathryn Edwards",
      },
    ],
    greeting: "Hello, Eliza Hogan! You have 5 unread messages.",
    favoriteFruit: "strawberry",
  },
];

export const value = someData[0].name;
